name: k6 Performance Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run k6 Smoke Users
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test/smoke-users.js

      - name: Run k6 Smoke Products
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test/smoke-products.js